name: magic
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10

  - pytorch==2.3.1
  - pytorch-cuda==12.4

  - pip:
    - -e ./MinerU --extra-index-url https://wheels.myhloli.com
